# https://github.com/Homebrew/homebrew-bundle
# 1. brew tap homebrew/bundle
# 2. brew bundle -v

tap 'homebrew/core'
tap 'homebrew/bundle'
tap 'homebrew/services'
tap 'caskroom/cask'
tap 'dotzero/tap'
brew 'ack'
brew 'bcrypt'
brew 'bx'
brew 'ctop'
brew 'dep'
brew 'dnsmasq', restart_service: true
brew 'dotzero/tap/git-profile'
brew 'git'
brew 'gnupg'
brew 'go'
brew 'httpie'
brew 'hugo'
brew 'jq'
brew 'mas'
brew 'mcrypt'
brew 'memcached'
brew 'micro'
brew 'mongodb', restart_service: true
brew 'nmap'
brew 'node'
brew 'p7zip'
brew 'php@7.2'
brew 'pv'
brew 'python3'
brew 'redis', restart_service: true
brew 'ripgrep'
brew 'scrypt'
brew 'sqlite'
brew 'stern'
brew 'tmux'
brew 'ttyrec'
brew 'wget'
brew 'xz'
brew 'youtube-dl'
cask 'appcleaner'
cask 'dash'
cask 'dripcap'
cask 'handbrake'
cask 'imageoptim'
cask 'java'
cask 'keybase'
cask 'mac2imgur'
cask 'macdown'
cask 'numi'
cask 'transmission'
cask 'vlc'
cask 'wireshark'
