# https://github.com/topgrade-rs/topgrade/blob/main/config.example.toml
[misc]
only = ["brew_cask", "brew_formula", "git_repos"]
cleanup = true
skip_notify = true

[git]
repos = [
   "~/.0"
]

[post_commands]
"brew prune" = "brew cleanup --prune=all"
